plugins {
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "ae2-batchcraft-${minecraft_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version as int)
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = false

    runs {
        configureEach {
            workingDirectory project.file('run')
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        client { }
        server {
            args '--nogui'
        }
    }
}

def loaderRepositories = repositories.toList()
repositories.clear()
repositories.maven {
    name = 'forgeReleases'
    url = 'https://maven.minecraftforge.net/releases'
}
loaderRepositories.each { repositories.add(it) }
repositories.maven {
    url = 'https://modmaven.dev/'
}

dependencies {
    implementation project(':shared')
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("appeng:appliedenergistics2:${ae2_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.4:processor'
    testImplementation 'junit:junit:4.13.2'
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

sourceSets {
    main {
        java.setSrcDirs(['src/main/java'])
    }
}

evaluationDependsOn(':shared')

tasks.named('jar', Jar) {
    from(project(':shared').sourceSets.main.output)
    archiveVersion.set("${mod_version}-forge")
    manifest {
        attributes([
                'Specification-Title': mod_name,
                'Specification-Vendor': 'AE2BC',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'AE2BC',
                'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}
