plugins {
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "ae2-batchcraft-${minecraft_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version as int)
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = false

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        client { }
        server {
            args '--nogui'
        }
    }
}

repositories {
    maven {
        url = 'https://api.modrinth.com/maven'
    }
}

dependencies {
    implementation project(':shared')
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("maven.modrinth:ae2:${ae2_version}")
    implementation fg.deobf("maven.modrinth:guideme:${guideme_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-api:2.0.9'
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

evaluationDependsOn(':shared')

tasks.named('test', Test) {
    useJUnitPlatform()
}

tasks.named('jar', Jar) {
    from(project(':shared').sourceSets.main.output)
    archiveVersion.set("${mod_version}-forge")
    manifest {
        attributes([
                'Specification-Title': mod_name,
                'Specification-Vendor': 'AE2BC',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'AE2BC',
                'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}
