plugins {
    id 'java-library'
}

version = 'unspecified'
group = findProperty('mod_group_id') ?: 'cn.ae2bc'
sourceCompatibility = targetCompatibility = '8'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version as int)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
